### ISSUE TITLE
Cannot compile with rustc 1.64

### ISSUE THREAD

**Issue by GregoryTravis** [chaosprint/daisy-rust-playground#1]
I am using rustc 1.64. `cargo build` gives me this:

```
   Compiling daisy-rust-playground v0.1.0 (/Users/gmt/pedal/daisy-rust-playground)
error: `#[alloc_error_handler]` function required, but not found

note: use `#![feature(default_alloc_error_handler)]` for a default error handler
```

If I add the suggested line, and then `cargo +nightly build`, I get this:

```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /Users/gmt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.47/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

   Compiling paste v1.0.9
```

**Comment by chaosprint** [comment]
Can you try to use a newer version of Rust like 1.67 stable?

I don't have the board around me but I can test it when I get the board back.

**Comment by GregoryTravis** [comment]
With 1.67, I get this:

```
   ....
   Compiling num_enum v0.5.7
   Compiling stm32h7xx-hal v0.13.0
   Compiling daisy-rust-playground v0.1.0 (/Users/gmt/pedal/daisy-rust-playground)
error: could not compile `daisy-rust-playground` due to 2 previous errors
error: Failed to parse crate metadata
```

With 1.75, I get this:

```
   ...
   Compiling cortex-m-semihosting v0.3.7
   Compiling log v0.4.17
   Compiling ahash v0.8.3
error: could not compile `proc-macro2` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: Failed to parse crate metadata
```

**Comment by chaosprint** [comment]
I just tested it with stable version:
```
rustc 1.74.1 (a28077b28 2023-12-04)
```
and everything works fine

**Comment by chaosprint** [comment]
aha, I see you should not use `cargo build`. check the readme and follow them step by step.
